// Copyright (c) 2022-2026 Chris Pulman. All rights reserved.
// Chris Pulman licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ModbusRx.Generators;

/// <summary>Generates Modbus-backed reactive properties and observable streams.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class ModbusReactiveStreamGenerator : IIncrementalGenerator
{
    /// <summary>Contains the generated attribute declarations consumed by the source generator.</summary>
    private const string AttributeSource = """
// <auto-generated />
#nullable enable
namespace ModbusRx.Generators
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class ModbusReactiveDeviceAttribute : global::System.Attribute
    {
        public string ConnectionMember { get; set; } = "MasterStream";

        public byte SlaveAddress { get; set; } = 1;

        public double DefaultInterval { get; set; } = 1000.0;

        public ModbusReactiveMasterKind MasterKind { get; set; }
    }

    public enum ModbusReactiveMasterKind
    {
        Auto,
        Ip,
        Serial,
    }

    public enum ModbusReactiveDataType
    {
        Auto,
        Bool,
        UInt16,
        Int16,
        UInt32,
        Int32,
        Float32,
        Float64,
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal abstract class ModbusReactivePointAttribute : global::System.Attribute
    {
        protected ModbusReactivePointAttribute(ushort address)
        {
            Address = address;
        }

        public ushort Address { get; }

        public ushort Count { get; set; }

        public ModbusReactiveDataType DataType { get; set; }

        public bool SwapWords { get; set; } = true;
    }

    internal sealed class HoldingRegisterAttribute : ModbusReactivePointAttribute
    {
        public HoldingRegisterAttribute(ushort address)
            : base(address)
        {
        }
    }

    internal sealed class InputRegisterAttribute : ModbusReactivePointAttribute
    {
        public InputRegisterAttribute(ushort address)
            : base(address)
        {
        }
    }

    internal sealed class CoilAttribute : ModbusReactivePointAttribute
    {
        public CoilAttribute(ushort address)
            : base(address)
        {
        }
    }

    internal sealed class DiscreteInputAttribute : ModbusReactivePointAttribute
    {
        public DiscreteInputAttribute(ushort address)
            : base(address)
        {
        }
    }
}
""";

    /// <summary>Diagnostic reported when a reactive device class is not partial.</summary>
    private static readonly DiagnosticDescriptor ClassMustBePartial = new(
        "MBRXGEN001",
        "Reactive Modbus device must be partial",
        "Class '{0}' must be partial to receive generated Modbus stream members",
        "ModbusRx.Generators",
        DiagnosticSeverity.Error,
        true);

    /// <summary>Diagnostic reported when a reactive Modbus property is not partial.</summary>
    private static readonly DiagnosticDescriptor PropertyMustBePartial = new(
        "MBRXGEN002",
        "Reactive Modbus property must be partial",
        "Property '{0}' must be partial so the generator can implement it",
        "ModbusRx.Generators",
        DiagnosticSeverity.Error,
        true);

    /// <summary>Diagnostic reported when a reactive Modbus property type cannot be converted.</summary>
    private static readonly DiagnosticDescriptor UnsupportedPropertyType = new(
        "MBRXGEN003",
        "Unsupported Modbus property type",
        "Property '{0}' has unsupported type '{1}' for {2}",
        "ModbusRx.Generators",
        DiagnosticSeverity.Error,
        true);

    /// <summary>Identifies the Modbus data source used by a generated reactive point.</summary>
    private enum ModbusPointKind
    {
        /// <summary>No supported Modbus point attribute was found.</summary>
        None,

        /// <summary>A holding register point.</summary>
        HoldingRegister,

        /// <summary>An input register point.</summary>
        InputRegister,

        /// <summary>A coil point.</summary>
        Coil,

        /// <summary>A discrete input point.</summary>
        DiscreteInput,
    }

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("ModbusReactiveAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var points = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is PropertyDeclarationSyntax property && property.AttributeLists.Count > 0,
                static (syntaxContext, _) => CreatePoint(syntaxContext))
            .Where(static point => point is not null)
            .Collect();

        context.RegisterSourceOutput(points, static (sourceContext, collectedPoints) => Execute(sourceContext, collectedPoints!));
    }

    /// <summary>Creates a Modbus point model from a property syntax context.</summary>
    /// <param name="context">The generator syntax context.</param>
    /// <returns>The point model when the property is decorated with a Modbus point attribute.</returns>
    private static ModbusPoint? CreatePoint(GeneratorSyntaxContext context)
    {
        var propertySyntax = (PropertyDeclarationSyntax)context.Node;
        var propertySymbol = context.SemanticModel.GetDeclaredSymbol(propertySyntax);
        if (propertySymbol is null || propertySymbol.ContainingType is null)
        {
            return null;
        }

        var pointAttribute = FindPointAttribute(propertySymbol);
        if (pointAttribute.Attribute is null)
        {
            return null;
        }

        var deviceAttribute = FindDeviceAttribute(propertySymbol.ContainingType);
        if (deviceAttribute is null)
        {
            return null;
        }

        var device = DeviceOptions.From(deviceAttribute);
        device = device.WithApiRoot(ResolveApiRoot(propertySymbol.ContainingType, device.ConnectionMember));
        return new ModbusPoint(
            propertySymbol,
            propertySyntax,
            propertySymbol.ContainingType,
            pointAttribute.Kind,
            GetPointAddress(pointAttribute.Attribute),
            device,
            PointOptions.From(pointAttribute.Attribute));
    }

    /// <summary>Finds the first supported point attribute on a property.</summary>
    /// <param name="propertySymbol">The property symbol.</param>
    /// <returns>The point attribute and kind when one is present.</returns>
    private static (AttributeData? Attribute, ModbusPointKind Kind) FindPointAttribute(IPropertySymbol propertySymbol)
    {
        foreach (var attribute in propertySymbol.GetAttributes())
        {
            var kind = GetPointKind(attribute.AttributeClass);
            if (kind == ModbusPointKind.None)
            {
                continue;
            }

            return (attribute, kind);
        }

        return (null, ModbusPointKind.None);
    }

    /// <summary>Finds the generated device attribute on a class.</summary>
    /// <param name="classSymbol">The class symbol.</param>
    /// <returns>The device attribute when present.</returns>
    private static AttributeData? FindDeviceAttribute(INamedTypeSymbol classSymbol)
    {
        foreach (var attribute in classSymbol.GetAttributes())
        {
            if (IsNamed(attribute.AttributeClass, "ModbusReactiveDeviceAttribute"))
            {
                return attribute;
            }
        }

        return null;
    }

    /// <summary>Gets the point address from the point attribute constructor.</summary>
    /// <param name="attribute">The point attribute.</param>
    /// <returns>The configured Modbus address.</returns>
    private static ushort GetPointAddress(AttributeData attribute) =>
        attribute.ConstructorArguments.Length > 0 &&
        attribute.ConstructorArguments[0].Value is ushort typedAddress
            ? typedAddress
            : (ushort)0;

    /// <summary>Emits source for each reactive Modbus device class represented by the collected points.</summary>
    /// <param name="context">The source production context.</param>
    /// <param name="points">The collected Modbus points.</param>
    private static void Execute(SourceProductionContext context, ImmutableArray<ModbusPoint> points)
    {
        foreach (var group in GroupPointsByClass(points))
        {
            if (!TryGetClassSyntax(context, group.Key, group.Value[0], out _))
            {
                continue;
            }

            var validPoints = GetValidPoints(context, group.Value);
            if (validPoints.Count == 0)
            {
                continue;
            }

            var source = EmitClass(group.Key, validPoints);
            context.AddSource($"{group.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty).Replace('.', '_')}.ModbusReactive.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    /// <summary>Groups Modbus points by their containing class.</summary>
    /// <param name="points">The points to group.</param>
    /// <returns>A dictionary keyed by containing class symbol.</returns>
    private static Dictionary<INamedTypeSymbol, List<ModbusPoint>> GroupPointsByClass(ImmutableArray<ModbusPoint> points)
    {
        var groupedPoints = new Dictionary<INamedTypeSymbol, List<ModbusPoint>>(SymbolEqualityComparer.Default);
        foreach (var point in points)
        {
            if (!groupedPoints.TryGetValue(point.ClassSymbol, out var classPoints))
            {
                classPoints = [];
                groupedPoints.Add(point.ClassSymbol, classPoints);
            }

            classPoints.Add(point);
        }

        return groupedPoints;
    }

    /// <summary>Attempts to resolve and validate the declaration syntax for a generated class.</summary>
    /// <param name="context">The source production context.</param>
    /// <param name="classSymbol">The class symbol.</param>
    /// <param name="firstPoint">The first point declared by the class.</param>
    /// <param name="classSyntax">The resolved class declaration syntax.</param>
    /// <returns>True when the class syntax is available and partial.</returns>
    private static bool TryGetClassSyntax(
        SourceProductionContext context,
        INamedTypeSymbol classSymbol,
        ModbusPoint firstPoint,
        out ClassDeclarationSyntax? classSyntax)
    {
        classSyntax = firstPoint.PropertySyntax.FirstAncestorOrSelf<ClassDeclarationSyntax>();
        if (classSyntax is null)
        {
            return false;
        }

        if (HasPartialModifier(classSyntax.Modifiers))
        {
            return true;
        }

        context.ReportDiagnostic(Diagnostic.Create(ClassMustBePartial, classSyntax.Identifier.GetLocation(), classSymbol.Name));
        return false;
    }

    /// <summary>Creates generated point models for points that pass syntax and type validation.</summary>
    /// <param name="context">The source production context.</param>
    /// <param name="points">The candidate points for one class.</param>
    /// <returns>The generated point models.</returns>
    private static List<GeneratedPoint> GetValidPoints(SourceProductionContext context, IReadOnlyList<ModbusPoint> points)
    {
        var validPoints = new List<GeneratedPoint>();
        foreach (var point in points)
        {
            if (!HasPartialModifier(point.PropertySyntax.Modifiers))
            {
                context.ReportDiagnostic(Diagnostic.Create(PropertyMustBePartial, point.PropertySyntax.Identifier.GetLocation(), point.PropertySymbol.Name));
                continue;
            }

            var typeInfo = ModbusTypeInfo.Create(point.PropertySymbol.Type, point.Kind, point.DeviceOptions.ApiRoot);
            if (typeInfo is null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedPropertyType,
                    point.PropertySyntax.Type.GetLocation(),
                    point.PropertySymbol.Name,
                    point.PropertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    point.Kind));
                continue;
            }

            validPoints.Add(new GeneratedPoint(point, typeInfo));
        }

        return validPoints;
    }

    /// <summary>Determines whether a modifier list contains the partial keyword.</summary>
    /// <param name="modifiers">The syntax modifiers.</param>
    /// <returns>True when the list contains a partial modifier.</returns>
    private static bool HasPartialModifier(SyntaxTokenList modifiers)
    {
        foreach (var modifier in modifiers)
        {
            if (modifier.IsKind(SyntaxKind.PartialKeyword))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>Emits the generated partial class source.</summary>
    /// <param name="classSymbol">The class symbol.</param>
    /// <param name="points">The generated points for the class.</param>
    /// <returns>The generated class source.</returns>
    private static string EmitClass(INamedTypeSymbol classSymbol, IReadOnlyList<GeneratedPoint> points)
    {
        var builder = new StringBuilder();
        _ = builder.AppendLine("// <auto-generated />");
        _ = builder.AppendLine("#nullable enable");

        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();
        if (namespaceName is not null)
        {
            _ = builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            _ = builder.AppendLine();
        }

        _ = builder.Append(GetAccessibility(classSymbol.DeclaredAccessibility)).Append(" partial class ").AppendLine(classSymbol.Name);
        _ = builder.AppendLine("{");

        foreach (var point in points)
        {
            EmitProperty(builder, point);
        }

        _ = builder.AppendLine("    public global::System.IDisposable BindGeneratedModbusStreams()");
        _ = builder.AppendLine("    {");
        _ = builder.AppendLine("        var disposables = new global::ReactiveUI.Primitives.Disposables.MultipleDisposable();");
        _ = builder.AppendLine("        BindGeneratedModbusStreams(disposables);");
        _ = builder.AppendLine("        return disposables;");
        _ = builder.AppendLine("    }");
        _ = builder.AppendLine();
        _ = builder.AppendLine("    public global::ReactiveUI.Primitives.Disposables.MultipleDisposable BindGeneratedModbusStreams(global::ReactiveUI.Primitives.Disposables.MultipleDisposable disposables)");
        _ = builder.AppendLine("    {");
        _ = builder.AppendLine("        if (disposables is null)");
        _ = builder.AppendLine("        {");
        _ = builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(disposables));");
        _ = builder.AppendLine("        }");
        _ = builder.AppendLine();

        foreach (var point in points)
        {
            EmitSubscription(builder, point);
        }

        _ = builder.AppendLine("        return disposables;");
        _ = builder.AppendLine("    }");

        EmitObserver(builder);

        foreach (var point in points)
        {
            EmitConversion(builder, point);
        }

        _ = builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>Emits the backing field, property implementation, and observable for a generated point.</summary>
    /// <param name="builder">The source builder.</param>
    /// <param name="point">The generated point.</param>
    private static void EmitProperty(StringBuilder builder, GeneratedPoint point)
    {
        var propertyName = point.Point.PropertySymbol.Name;
        var typeName = point.Type.TypeName;
        var fieldName = ToFieldName(propertyName);
        var subjectName = fieldName + "Subject";

        _ = builder.AppendLine();
        _ = builder.Append("    private ").Append(typeName).Append(' ').Append(fieldName).AppendLine(" = default!;");
        _ = builder.Append("    private readonly global::ReactiveUI.Primitives.Signals.ReplaySignal<").Append(typeName).Append("> ").Append(subjectName).Append(" = new global::ReactiveUI.Primitives.Signals.ReplaySignal<").Append(typeName).AppendLine(">(1);");
        _ = builder.AppendLine();
        _ = builder.Append("    ").Append(GetAccessibility(point.Point.PropertySymbol.DeclaredAccessibility)).Append(" partial ").Append(typeName).Append(' ').AppendLine(propertyName);
        _ = builder.AppendLine("    {");
        _ = builder.Append("        get => ").Append(fieldName).AppendLine(";");
        _ = builder.AppendLine("        private set");
        _ = builder.AppendLine("        {");
        _ = builder.Append("            if (global::System.Collections.Generic.EqualityComparer<").Append(typeName).Append(">.Default.Equals(").Append(fieldName).AppendLine(", value))");
        _ = builder.AppendLine("            {");
        _ = builder.AppendLine("                return;");
        _ = builder.AppendLine("            }");
        _ = builder.AppendLine();
        _ = builder.Append("            ").Append(fieldName).AppendLine(" = value;");
        _ = builder.Append("            ").Append(subjectName).AppendLine(".OnNext(value);");
        _ = builder.AppendLine("        }");
        _ = builder.AppendLine("    }");
        _ = builder.AppendLine();
        _ = builder.Append("    public global::System.IObservable<").Append(typeName).Append("> ").Append(propertyName).Append("Observable => ").Append(subjectName).AppendLine(";");
        _ = builder.Append("    public global::System.Exception? ").Append(propertyName).AppendLine("Error { get; private set; }");
    }

    /// <summary>Emits the binding subscription for a generated point.</summary>
    /// <param name="builder">The source builder.</param>
    /// <param name="point">The generated point.</param>
    private static void EmitSubscription(StringBuilder builder, GeneratedPoint point)
    {
        var propertyName = point.Point.PropertySymbol.Name;
        var readMethod = GetReadMethod(point.Point.Kind);
        var count = point.Point.PointOptions.Count == 0 ? point.Type.RegisterCount : point.Point.PointOptions.Count;
        var connectionMember = point.Point.DeviceOptions.ConnectionMember;
        var interval = point.Point.DeviceOptions.DefaultInterval.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var resultType = point.Point.Kind is ModbusPointKind.Coil or ModbusPointKind.DiscreteInput
            ? "(bool[]? data, global::System.Exception? error)"
            : "(ushort[]? data, global::System.Exception? error)";

        _ = builder.Append("        disposables.Add(").Append(point.Point.DeviceOptions.ApiRoot).Append(".Create.").Append(readMethod).Append("(this.").Append(connectionMember).Append(", ");
        if (point.Point.DeviceOptions.MasterKind == "Serial")
        {
            _ = builder.Append("(byte)").Append(point.Point.DeviceOptions.SlaveAddress).Append(", ");
        }

        _ = builder.Append(point.Point.Address).Append(", ").Append(count).Append(", ").Append(interval).Append(").Subscribe(new GeneratedModbusObserver<").Append(resultType).AppendLine(">(result =>");
        _ = builder.AppendLine("        {");
        _ = builder.Append("            ").Append(propertyName).AppendLine("Error = result.error;");
        _ = builder.Append("            if (result.error is null && result.data is not null && result.data.Length >= ").Append(count).AppendLine(")");
        _ = builder.AppendLine("            {");
        _ = builder.Append("                ").Append(propertyName).Append(" = Convert").Append(propertyName).AppendLine("(result.data);");
        _ = builder.AppendLine("            }");
        _ = builder.AppendLine("        })));");
        _ = builder.AppendLine();
    }

    /// <summary>Emits the observer adapter used by generated subscriptions.</summary>
    /// <param name="builder">The source builder.</param>
    private static void EmitObserver(StringBuilder builder)
    {
        _ = builder.AppendLine();
        _ = builder.AppendLine("    private sealed class GeneratedModbusObserver<T> : global::System.IObserver<T>");
        _ = builder.AppendLine("    {");
        _ = builder.AppendLine("        private readonly global::System.Action<T> _onNext;");
        _ = builder.AppendLine();
        _ = builder.AppendLine("        public GeneratedModbusObserver(global::System.Action<T> onNext)");
        _ = builder.AppendLine("        {");
        _ = builder.AppendLine("            _onNext = onNext ?? throw new global::System.ArgumentNullException(nameof(onNext));");
        _ = builder.AppendLine("        }");
        _ = builder.AppendLine();
        _ = builder.AppendLine("        public void OnCompleted()");
        _ = builder.AppendLine("        {");
        _ = builder.AppendLine("        }");
        _ = builder.AppendLine();
        _ = builder.AppendLine("        public void OnError(global::System.Exception error)");
        _ = builder.AppendLine("        {");
        _ = builder.AppendLine("        }");
        _ = builder.AppendLine();
        _ = builder.AppendLine("        public void OnNext(T value) => _onNext(value);");
        _ = builder.AppendLine("    }");
    }

    /// <summary>Emits the conversion method for a generated point.</summary>
    /// <param name="builder">The source builder.</param>
    /// <param name="point">The generated point.</param>
    private static void EmitConversion(StringBuilder builder, GeneratedPoint point)
    {
        var propertyName = point.Point.PropertySymbol.Name;
        var typeName = point.Type.TypeName;
        var methodName = point.Point.Kind is ModbusPointKind.Coil or ModbusPointKind.DiscreteInput
            ? "bool[]"
            : "ushort[]";

        _ = builder.AppendLine();
        _ = builder.Append("    private static ").Append(typeName).Append(" Convert").Append(propertyName).Append('(').Append(methodName).AppendLine(" data)");
        _ = builder.AppendLine("    {");
        _ = builder.Append("        return ").Append(point.Type.GetConversionExpression("data", point.Point.PointOptions.SwapWords)).AppendLine(";");
        _ = builder.AppendLine("    }");
    }

    /// <summary>Gets the Create API read method name for a Modbus point kind.</summary>
    /// <param name="kind">The point kind.</param>
    /// <returns>The read method name.</returns>
    private static string GetReadMethod(ModbusPointKind kind) =>
        kind switch
        {
            ModbusPointKind.HoldingRegister => "ReadHoldingRegisters",
            ModbusPointKind.InputRegister => "ReadInputRegisters",
            ModbusPointKind.Coil => "ReadCoils",
            ModbusPointKind.DiscreteInput => "ReadInputs",
            _ => throw new InvalidOperationException("Unsupported point kind."),
        };

    /// <summary>Gets a source accessibility keyword for a Roslyn accessibility value.</summary>
    /// <param name="accessibility">The Roslyn accessibility value.</param>
    /// <returns>The generated source accessibility keyword.</returns>
    private static string GetAccessibility(Accessibility accessibility) =>
        accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal",
        };

    /// <summary>Gets the Modbus point kind represented by an attribute type.</summary>
    /// <param name="attributeType">The attribute type symbol.</param>
    /// <returns>The matching point kind, or none when the attribute is unsupported.</returns>
    private static ModbusPointKind GetPointKind(INamedTypeSymbol? attributeType)
    {
        if (IsNamed(attributeType, "HoldingRegisterAttribute"))
        {
            return ModbusPointKind.HoldingRegister;
        }

        if (IsNamed(attributeType, "InputRegisterAttribute"))
        {
            return ModbusPointKind.InputRegister;
        }

        if (IsNamed(attributeType, "CoilAttribute"))
        {
            return ModbusPointKind.Coil;
        }

        return IsNamed(attributeType, "DiscreteInputAttribute") ? ModbusPointKind.DiscreteInput : ModbusPointKind.None;
    }

    /// <summary>Determines whether a symbol has the expected generated attribute name.</summary>
    /// <param name="symbol">The symbol to check.</param>
    /// <param name="metadataName">The expected metadata name.</param>
    /// <returns>True when the symbol matches the generated attribute namespace and name.</returns>
    private static bool IsNamed(INamedTypeSymbol? symbol, string metadataName) =>
        symbol?.Name == metadataName && symbol.ContainingNamespace.ToDisplayString() == "ModbusRx.Generators";

    /// <summary>Resolves the generated API root namespace from the configured connection member.</summary>
    /// <param name="classSymbol">The class symbol that declares the connection member.</param>
    /// <param name="connectionMember">The configured connection member name.</param>
    /// <returns>The generated API root namespace.</returns>
    private static string ResolveApiRoot(INamedTypeSymbol classSymbol, string connectionMember)
    {
        ITypeSymbol? memberType = null;
        foreach (var member in classSymbol.GetMembers(connectionMember))
        {
            memberType = member switch
            {
                IPropertySymbol property => property.Type,
                IFieldSymbol field => field.Type,
                _ => null,
            };

            if (memberType is not null)
            {
                break;
            }
        }

        var typeName = memberType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? string.Empty;
        return typeName.Contains("global::ModbusRx.Reactive.Device.", StringComparison.Ordinal)
            ? "global::ModbusRx.Reactive"
            : "global::ModbusRx";
    }

    /// <summary>Creates the generated backing field name for a property.</summary>
    /// <param name="propertyName">The property name.</param>
    /// <returns>The generated backing field name.</returns>
    private static string ToFieldName(string propertyName) =>
        "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Remove(0, 1);

    /// <summary>Describes a source property decorated as a Modbus reactive point.</summary>
    /// <param name="propertySymbol">The property symbol.</param>
    /// <param name="propertySyntax">The property syntax.</param>
    /// <param name="classSymbol">The containing class symbol.</param>
    /// <param name="kind">The Modbus point kind.</param>
    /// <param name="address">The Modbus address.</param>
    /// <param name="deviceOptions">The device options.</param>
    /// <param name="pointOptions">The point options.</param>
    private sealed class ModbusPoint(
        IPropertySymbol propertySymbol,
        PropertyDeclarationSyntax propertySyntax,
        INamedTypeSymbol classSymbol,
        ModbusPointKind kind,
        ushort address,
        DeviceOptions deviceOptions,
        PointOptions pointOptions)
    {
        /// <summary>Gets the property symbol.</summary>
        public IPropertySymbol PropertySymbol { get; } = propertySymbol;

        /// <summary>Gets the property declaration syntax.</summary>
        public PropertyDeclarationSyntax PropertySyntax { get; } = propertySyntax;

        /// <summary>Gets the containing class symbol.</summary>
        public INamedTypeSymbol ClassSymbol { get; } = classSymbol;

        /// <summary>Gets the Modbus point kind.</summary>
        public ModbusPointKind Kind { get; } = kind;

        /// <summary>Gets the Modbus address.</summary>
        public ushort Address { get; } = address;

        /// <summary>Gets the device options.</summary>
        public DeviceOptions DeviceOptions { get; } = deviceOptions;

        /// <summary>Gets the point options.</summary>
        public PointOptions PointOptions { get; } = pointOptions;
    }

    /// <summary>Combines a source point with its generated type information.</summary>
    /// <param name="point">The source point.</param>
    /// <param name="type">The generated type information.</param>
    private sealed class GeneratedPoint(ModbusPoint point, ModbusTypeInfo type)
    {
        /// <summary>Gets the source point.</summary>
        public ModbusPoint Point { get; } = point;

        /// <summary>Gets the generated type information.</summary>
        public ModbusTypeInfo Type { get; } = type;
    }

    /// <summary>Contains generator options read from a device attribute.</summary>
    /// <param name="connectionMember">The connection member name.</param>
    /// <param name="slaveAddress">The slave address.</param>
    /// <param name="defaultInterval">The default polling interval.</param>
    /// <param name="masterKind">The master kind.</param>
    /// <param name="apiRoot">The generated API root namespace.</param>
    private sealed class DeviceOptions(string connectionMember, byte slaveAddress, double defaultInterval, string masterKind, string apiRoot)
    {
        /// <summary>Gets the connection member name.</summary>
        public string ConnectionMember { get; } = connectionMember;

        /// <summary>Gets the slave address.</summary>
        public byte SlaveAddress { get; } = slaveAddress;

        /// <summary>Gets the default polling interval.</summary>
        public double DefaultInterval { get; } = defaultInterval;

        /// <summary>Gets the master kind.</summary>
        public string MasterKind { get; } = masterKind;

        /// <summary>Gets the generated API root namespace.</summary>
        public string ApiRoot { get; } = apiRoot;

        /// <summary>Creates device options from a generated device attribute.</summary>
        /// <param name="attribute">The device attribute data.</param>
        /// <returns>The device options.</returns>
        public static DeviceOptions From(AttributeData attribute)
        {
            var connectionMember = "MasterStream";
            var slaveAddress = (byte)1;
            var defaultInterval = 1000.0;
            var masterKind = "Auto";

            foreach (var argument in attribute.NamedArguments)
            {
                switch (argument.Key)
                {
                    case "ConnectionMember" when argument.Value.Value is string value:
                        {
                            connectionMember = value;
                            break;
                        }

                    case "SlaveAddress" when argument.Value.Value is byte value:
                        {
                            slaveAddress = value;
                            break;
                        }

                    case "DefaultInterval" when argument.Value.Value is double value:
                        {
                            defaultInterval = value;
                            break;
                        }

                    case "MasterKind" when argument.Value.Value is int value:
                        {
                            masterKind = value switch
                            {
                                2 => "Serial",
                                1 => "Ip",
                                _ => "Auto",
                            };

                            break;
                        }
                }
            }

            return new DeviceOptions(connectionMember, slaveAddress, defaultInterval, masterKind, "global::ModbusRx");
        }

        /// <summary>Creates a copy with a resolved API root namespace.</summary>
        /// <param name="apiRoot">The API root namespace.</param>
        /// <returns>The updated device options.</returns>
        public DeviceOptions WithApiRoot(string apiRoot) =>
            new(ConnectionMember, SlaveAddress, DefaultInterval, MasterKind, apiRoot);
    }

    /// <summary>Contains generator options read from a point attribute.</summary>
    /// <param name="count">The configured register or coil count.</param>
    /// <param name="swapWords">Whether register words are swapped for multi-register values.</param>
    private sealed class PointOptions(ushort count, bool swapWords)
    {
        /// <summary>Gets the configured register or coil count.</summary>
        public ushort Count { get; } = count;

        /// <summary>Gets a value indicating whether register words are swapped for multi-register values.</summary>
        public bool SwapWords { get; } = swapWords;

        /// <summary>Creates point options from a generated point attribute.</summary>
        /// <param name="attribute">The point attribute data.</param>
        /// <returns>The point options.</returns>
        public static PointOptions From(AttributeData attribute)
        {
            var count = (ushort)0;
            var swapWords = true;

            foreach (var argument in attribute.NamedArguments)
            {
                switch (argument.Key)
                {
                    case "Count" when argument.Value.Value is ushort value:
                        {
                            count = value;
                            break;
                        }

                    case "SwapWords" when argument.Value.Value is bool value:
                        {
                            swapWords = value;
                            break;
                        }
                }
            }

            return new PointOptions(count, swapWords);
        }
    }

    /// <summary>Contains generated conversion metadata for a Modbus property type.</summary>
    /// <param name="typeName">The generated type name.</param>
    /// <param name="registerCount">The number of registers required to read the value.</param>
    /// <param name="conversionFactory">The generated conversion expression factory.</param>
    private sealed class ModbusTypeInfo(string typeName, ushort registerCount, Func<string, bool, string> conversionFactory)
    {
        /// <summary>Gets the generated type name.</summary>
        public string TypeName { get; } = typeName;

        /// <summary>Gets the number of registers required to read the value.</summary>
        public ushort RegisterCount { get; } = registerCount;

        /// <summary>Creates conversion metadata for a property type and Modbus point kind.</summary>
        /// <param name="typeSymbol">The property type symbol.</param>
        /// <param name="pointKind">The point kind.</param>
        /// <param name="apiRoot">The generated API root namespace.</param>
        /// <returns>The type metadata when the property type is supported.</returns>
        public static ModbusTypeInfo? Create(ITypeSymbol typeSymbol, ModbusPointKind pointKind, string apiRoot)
        {
            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var underlying = Nullable.GetUnderlyingTypeName(typeSymbol) ?? typeName;
            var nullableCast = underlying == typeName ? string.Empty : "(" + typeName + ")";

            if (pointKind is ModbusPointKind.Coil or ModbusPointKind.DiscreteInput)
            {
                return underlying == "bool"
                    ? new ModbusTypeInfo(typeName, 1, (data, _) => nullableCast + data + "[0]")
                    : null;
            }

            return underlying switch
            {
                "ushort" => new ModbusTypeInfo(typeName, 1, (data, _) => nullableCast + data + "[0]"),
                "short" => new ModbusTypeInfo(typeName, 1, (data, _) => nullableCast + "unchecked((short)" + data + "[0])"),
                "uint" => new ModbusTypeInfo(typeName, 2, (data, swap) => nullableCast + ToUInt32Expression(data, swap)),
                "int" => new ModbusTypeInfo(typeName, 2, (data, swap) => nullableCast + "unchecked((int)" + ToUInt32Expression(data, swap) + ")"),
                "float" => new ModbusTypeInfo(typeName, 2, (data, swap) => nullableCast + apiRoot + ".Utility.ModbusUtility.ReadSingle(new global::System.ReadOnlySpan<ushort>(" + data + ", 0, 2), " + ToBoolLiteral(swap) + ")"),
                "double" => new ModbusTypeInfo(typeName, 4, (data, swap) => nullableCast + apiRoot + ".Utility.ModbusUtility.ReadDouble(new global::System.ReadOnlySpan<ushort>(" + data + ", 0, 4), " + ToBoolLiteral(swap) + ")"),
                _ => null,
            };
        }

        /// <summary>Gets the generated conversion expression for a source data variable.</summary>
        /// <param name="dataName">The source data variable name.</param>
        /// <param name="swapWords">Whether multi-register words should be swapped.</param>
        /// <returns>The generated conversion expression.</returns>
        public string GetConversionExpression(string dataName, bool swapWords) => conversionFactory(dataName, swapWords);

        /// <summary>Creates a generated expression that converts two registers to a 32-bit unsigned integer.</summary>
        /// <param name="data">The source data variable name.</param>
        /// <param name="swapWords">Whether register words should be swapped.</param>
        /// <returns>The generated conversion expression.</returns>
        private static string ToUInt32Expression(string data, bool swapWords)
        {
            var high = swapWords ? data + "[1]" : data + "[0]";
            var low = swapWords ? data + "[0]" : data + "[1]";
            return "(((uint)" + high + " << 16) | " + low + ")";
        }

        /// <summary>Converts a boolean value to a generated C# literal.</summary>
        /// <param name="value">The value to convert.</param>
        /// <returns>The generated C# literal.</returns>
        private static string ToBoolLiteral(bool value) => value ? "true" : "false";
    }
}
