// Copyright (c) Chris Pulman. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ModbusRx.Generators;

/// <summary>
/// Generates Modbus-backed reactive properties and observable streams.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ModbusReactiveStreamGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
// <auto-generated />
#nullable enable
namespace ModbusRx.Generators
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class ModbusReactiveDeviceAttribute : global::System.Attribute
    {
        public string ConnectionMember { get; set; } = "MasterStream";

        public byte SlaveAddress { get; set; } = 1;

        public double DefaultInterval { get; set; } = 1000.0;

        public ModbusReactiveMasterKind MasterKind { get; set; }
    }

    public enum ModbusReactiveMasterKind
    {
        Auto,
        Ip,
        Serial,
    }

    public enum ModbusReactiveDataType
    {
        Auto,
        Bool,
        UInt16,
        Int16,
        UInt32,
        Int32,
        Float32,
        Float64,
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal abstract class ModbusReactivePointAttribute : global::System.Attribute
    {
        protected ModbusReactivePointAttribute(ushort address)
        {
            Address = address;
        }

        public ushort Address { get; }

        public ushort Count { get; set; }

        public ModbusReactiveDataType DataType { get; set; }

        public bool SwapWords { get; set; } = true;
    }

    internal sealed class HoldingRegisterAttribute : ModbusReactivePointAttribute
    {
        public HoldingRegisterAttribute(ushort address)
            : base(address)
        {
        }
    }

    internal sealed class InputRegisterAttribute : ModbusReactivePointAttribute
    {
        public InputRegisterAttribute(ushort address)
            : base(address)
        {
        }
    }

    internal sealed class CoilAttribute : ModbusReactivePointAttribute
    {
        public CoilAttribute(ushort address)
            : base(address)
        {
        }
    }

    internal sealed class DiscreteInputAttribute : ModbusReactivePointAttribute
    {
        public DiscreteInputAttribute(ushort address)
            : base(address)
        {
        }
    }
}
""";

    private static readonly DiagnosticDescriptor ClassMustBePartial = new(
        "MBRXGEN001",
        "Reactive Modbus device must be partial",
        "Class '{0}' must be partial to receive generated Modbus stream members",
        "ModbusRx.Generators",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor PropertyMustBePartial = new(
        "MBRXGEN002",
        "Reactive Modbus property must be partial",
        "Property '{0}' must be partial so the generator can implement it",
        "ModbusRx.Generators",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor UnsupportedPropertyType = new(
        "MBRXGEN003",
        "Unsupported Modbus property type",
        "Property '{0}' has unsupported type '{1}' for {2}",
        "ModbusRx.Generators",
        DiagnosticSeverity.Error,
        true);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("ModbusReactiveAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var points = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is PropertyDeclarationSyntax property && property.AttributeLists.Count > 0,
                static (syntaxContext, _) => CreatePoint(syntaxContext))
            .Where(static point => point is not null)
            .Collect();

        context.RegisterSourceOutput(points, static (sourceContext, collectedPoints) => Execute(sourceContext, collectedPoints!));
    }

    private static ModbusPoint? CreatePoint(GeneratorSyntaxContext context)
    {
        var propertySyntax = (PropertyDeclarationSyntax)context.Node;
        var propertySymbol = context.SemanticModel.GetDeclaredSymbol(propertySyntax) as IPropertySymbol;
        if (propertySymbol is null || propertySymbol.ContainingType is null)
        {
            return null;
        }

        var pointAttribute = propertySymbol.GetAttributes()
            .Select(attribute => (Attribute: attribute, Kind: GetPointKind(attribute.AttributeClass)))
            .FirstOrDefault(item => item.Kind != ModbusPointKind.None);

        if (pointAttribute.Kind == ModbusPointKind.None)
        {
            return null;
        }

        var deviceAttribute = propertySymbol.ContainingType.GetAttributes()
            .FirstOrDefault(attribute => IsNamed(attribute.AttributeClass, "ModbusReactiveDeviceAttribute"));
        if (deviceAttribute is null)
        {
            return null;
        }

        var address = pointAttribute.Attribute.ConstructorArguments.Length > 0 &&
            pointAttribute.Attribute.ConstructorArguments[0].Value is ushort typedAddress
                ? typedAddress
                : (ushort)0;

        var device = DeviceOptions.From(deviceAttribute);
        var point = PointOptions.From(pointAttribute.Attribute);
        return new ModbusPoint(propertySymbol, propertySyntax, propertySymbol.ContainingType, pointAttribute.Kind, address, device, point);
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<ModbusPoint> points)
    {
        foreach (var group in points.GroupBy(point => point.ClassSymbol, SymbolEqualityComparer.Default))
        {
            if (group.Key is not INamedTypeSymbol classSymbol)
            {
                continue;
            }

            var classSyntax = group.First().PropertySyntax.FirstAncestorOrSelf<ClassDeclarationSyntax>();
            if (classSyntax is null)
            {
                continue;
            }

            if (!classSyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                context.ReportDiagnostic(Diagnostic.Create(ClassMustBePartial, classSyntax.Identifier.GetLocation(), classSymbol.Name));
                continue;
            }

            var validPoints = new List<GeneratedPoint>();
            foreach (var point in group)
            {
                if (!point.PropertySyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
                {
                    context.ReportDiagnostic(Diagnostic.Create(PropertyMustBePartial, point.PropertySyntax.Identifier.GetLocation(), point.PropertySymbol.Name));
                    continue;
                }

                var typeInfo = ModbusTypeInfo.Create(point.PropertySymbol.Type, point.Kind);
                if (typeInfo is null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        UnsupportedPropertyType,
                        point.PropertySyntax.Type.GetLocation(),
                        point.PropertySymbol.Name,
                        point.PropertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        point.Kind));
                    continue;
                }

                validPoints.Add(new GeneratedPoint(point, typeInfo));
            }

            if (validPoints.Count == 0)
            {
                continue;
            }

            var source = EmitClass(classSymbol, validPoints);
            context.AddSource($"{classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty).Replace('.', '_')}.ModbusReactive.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string EmitClass(INamedTypeSymbol classSymbol, IReadOnlyList<GeneratedPoint> points)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");

        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();
        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            builder.AppendLine();
        }

        builder.Append(GetAccessibility(classSymbol.DeclaredAccessibility)).Append(" partial class ").Append(classSymbol.Name).AppendLine();
        builder.AppendLine("{");

        foreach (var point in points)
        {
            EmitProperty(builder, point);
        }

        builder.AppendLine("    public global::System.IDisposable BindGeneratedModbusStreams()");
        builder.AppendLine("    {");
        builder.AppendLine("        var disposables = new global::System.Reactive.Disposables.CompositeDisposable();");
        builder.AppendLine("        BindGeneratedModbusStreams(disposables);");
        builder.AppendLine("        return disposables;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public global::System.Reactive.Disposables.CompositeDisposable BindGeneratedModbusStreams(global::System.Reactive.Disposables.CompositeDisposable disposables)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (disposables is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(disposables));");
        builder.AppendLine("        }");
        builder.AppendLine();

        foreach (var point in points)
        {
            EmitSubscription(builder, point);
        }

        builder.AppendLine("        return disposables;");
        builder.AppendLine("    }");

        foreach (var point in points)
        {
            EmitConversion(builder, point);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitProperty(StringBuilder builder, GeneratedPoint point)
    {
        var propertyName = point.Point.PropertySymbol.Name;
        var typeName = point.Type.TypeName;
        var fieldName = ToFieldName(propertyName);
        var subjectName = fieldName + "Subject";

        builder.AppendLine();
        builder.Append("    private ").Append(typeName).Append(' ').Append(fieldName).AppendLine(" = default!;");
        builder.Append("    private readonly global::System.Reactive.Subjects.ReplaySubject<").Append(typeName).Append("> ").Append(subjectName).Append(" = new global::System.Reactive.Subjects.ReplaySubject<").Append(typeName).AppendLine(">(1);");
        builder.AppendLine();
        builder.Append("    ").Append(GetAccessibility(point.Point.PropertySymbol.DeclaredAccessibility)).Append(" partial ").Append(typeName).Append(' ').Append(propertyName).AppendLine();
        builder.AppendLine("    {");
        builder.Append("        get => ").Append(fieldName).AppendLine(";");
        builder.AppendLine("        private set");
        builder.AppendLine("        {");
        builder.Append("            if (global::System.Collections.Generic.EqualityComparer<").Append(typeName).Append(">.Default.Equals(").Append(fieldName).AppendLine(", value))");
        builder.AppendLine("            {");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.Append("            ").Append(fieldName).AppendLine(" = value;");
        builder.Append("            ").Append(subjectName).AppendLine(".OnNext(value);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.Append("    public global::System.IObservable<").Append(typeName).Append("> ").Append(propertyName).Append("Observable => ").Append(subjectName).AppendLine(";");
        builder.Append("    public global::System.Exception? ").Append(propertyName).AppendLine("Error { get; private set; }");
    }

    private static void EmitSubscription(StringBuilder builder, GeneratedPoint point)
    {
        var propertyName = point.Point.PropertySymbol.Name;
        var readMethod = GetReadMethod(point.Point.Kind);
        var count = point.Point.PointOptions.Count == 0 ? point.Type.RegisterCount : point.Point.PointOptions.Count;
        var connectionMember = point.Point.DeviceOptions.ConnectionMember;
        var interval = point.Point.DeviceOptions.DefaultInterval.ToString(System.Globalization.CultureInfo.InvariantCulture);

        builder.Append("        disposables.Add(global::System.ObservableExtensions.Subscribe(global::ModbusRx.Reactive.Create.").Append(readMethod).Append("(this.").Append(connectionMember).Append(", ");
        if (point.Point.DeviceOptions.MasterKind == "Serial")
        {
            builder.Append("(byte)").Append(point.Point.DeviceOptions.SlaveAddress).Append(", ");
        }

        builder.Append(point.Point.Address).Append(", ").Append(count).Append(", ").Append(interval).AppendLine("), result =>");
        builder.AppendLine("        {");
        builder.Append("            ").Append(propertyName).AppendLine("Error = result.error;");
        builder.Append("            if (result.error is null && result.data is not null && result.data.Length >= ").Append(count).AppendLine(")");
        builder.AppendLine("            {");
        builder.Append("                ").Append(propertyName).Append(" = Convert").Append(propertyName).AppendLine("(result.data);");
        builder.AppendLine("            }");
        builder.AppendLine("        }));");
        builder.AppendLine();
    }

    private static void EmitConversion(StringBuilder builder, GeneratedPoint point)
    {
        var propertyName = point.Point.PropertySymbol.Name;
        var typeName = point.Type.TypeName;
        var methodName = point.Point.Kind is ModbusPointKind.Coil or ModbusPointKind.DiscreteInput
            ? "bool[]"
            : "ushort[]";

        builder.AppendLine();
        builder.Append("    private static ").Append(typeName).Append(" Convert").Append(propertyName).Append('(').Append(methodName).AppendLine(" data)");
        builder.AppendLine("    {");
        builder.Append("        return ").Append(point.Type.GetConversionExpression("data", point.Point.PointOptions.SwapWords)).AppendLine(";");
        builder.AppendLine("    }");
    }

    private static string GetReadMethod(ModbusPointKind kind) =>
        kind switch
        {
            ModbusPointKind.HoldingRegister => "ReadHoldingRegisters",
            ModbusPointKind.InputRegister => "ReadInputRegisters",
            ModbusPointKind.Coil => "ReadCoils",
            ModbusPointKind.DiscreteInput => "ReadInputs",
            _ => throw new InvalidOperationException("Unsupported point kind."),
        };

    private static string GetAccessibility(Accessibility accessibility) =>
        accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal",
        };

    private static ModbusPointKind GetPointKind(INamedTypeSymbol? attributeType)
    {
        if (IsNamed(attributeType, "HoldingRegisterAttribute"))
        {
            return ModbusPointKind.HoldingRegister;
        }

        if (IsNamed(attributeType, "InputRegisterAttribute"))
        {
            return ModbusPointKind.InputRegister;
        }

        if (IsNamed(attributeType, "CoilAttribute"))
        {
            return ModbusPointKind.Coil;
        }

        if (IsNamed(attributeType, "DiscreteInputAttribute"))
        {
            return ModbusPointKind.DiscreteInput;
        }

        return ModbusPointKind.None;
    }

    private static bool IsNamed(INamedTypeSymbol? symbol, string metadataName) =>
        symbol?.Name == metadataName && symbol.ContainingNamespace.ToDisplayString() == "ModbusRx.Generators";

    private static string ToFieldName(string propertyName) =>
        "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);

    private sealed class ModbusPoint(
        IPropertySymbol propertySymbol,
        PropertyDeclarationSyntax propertySyntax,
        INamedTypeSymbol classSymbol,
        ModbusPointKind kind,
        ushort address,
        DeviceOptions deviceOptions,
        PointOptions pointOptions)
    {
        public IPropertySymbol PropertySymbol { get; } = propertySymbol;

        public PropertyDeclarationSyntax PropertySyntax { get; } = propertySyntax;

        public INamedTypeSymbol ClassSymbol { get; } = classSymbol;

        public ModbusPointKind Kind { get; } = kind;

        public ushort Address { get; } = address;

        public DeviceOptions DeviceOptions { get; } = deviceOptions;

        public PointOptions PointOptions { get; } = pointOptions;
    }

    private sealed class GeneratedPoint(ModbusPoint point, ModbusTypeInfo type)
    {
        public ModbusPoint Point { get; } = point;

        public ModbusTypeInfo Type { get; } = type;
    }

    private sealed class DeviceOptions(string connectionMember, byte slaveAddress, double defaultInterval, string masterKind)
    {
        public string ConnectionMember { get; } = connectionMember;

        public byte SlaveAddress { get; } = slaveAddress;

        public double DefaultInterval { get; } = defaultInterval;

        public string MasterKind { get; } = masterKind;

        public static DeviceOptions From(AttributeData attribute)
        {
            var connectionMember = "MasterStream";
            var slaveAddress = (byte)1;
            var defaultInterval = 1000.0;
            var masterKind = "Auto";

            foreach (var argument in attribute.NamedArguments)
            {
                switch (argument.Key)
                {
                    case "ConnectionMember" when argument.Value.Value is string value:
                        connectionMember = value;
                        break;
                    case "SlaveAddress" when argument.Value.Value is byte value:
                        slaveAddress = value;
                        break;
                    case "DefaultInterval" when argument.Value.Value is double value:
                        defaultInterval = value;
                        break;
                    case "MasterKind" when argument.Value.Value is int value:
                        masterKind = value == 2 ? "Serial" : value == 1 ? "Ip" : "Auto";
                        break;
                }
            }

            return new DeviceOptions(connectionMember, slaveAddress, defaultInterval, masterKind);
        }
    }

    private sealed class PointOptions(ushort count, bool swapWords)
    {
        public ushort Count { get; } = count;

        public bool SwapWords { get; } = swapWords;

        public static PointOptions From(AttributeData attribute)
        {
            var count = (ushort)0;
            var swapWords = true;

            foreach (var argument in attribute.NamedArguments)
            {
                switch (argument.Key)
                {
                    case "Count" when argument.Value.Value is ushort value:
                        count = value;
                        break;
                    case "SwapWords" when argument.Value.Value is bool value:
                        swapWords = value;
                        break;
                }
            }

            return new PointOptions(count, swapWords);
        }
    }

    private sealed class ModbusTypeInfo(string typeName, ushort registerCount, Func<string, bool, string> conversionFactory)
    {
        public string TypeName { get; } = typeName;

        public ushort RegisterCount { get; } = registerCount;

        public string GetConversionExpression(string dataName, bool swapWords) => conversionFactory(dataName, swapWords);

        public static ModbusTypeInfo? Create(ITypeSymbol typeSymbol, ModbusPointKind pointKind)
        {
            var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var underlying = Nullable.GetUnderlyingTypeName(typeSymbol) ?? typeName;
            var nullableCast = underlying == typeName ? string.Empty : "(" + typeName + ")";

            if (pointKind is ModbusPointKind.Coil or ModbusPointKind.DiscreteInput)
            {
                return underlying == "bool"
                    ? new ModbusTypeInfo(typeName, 1, (data, _) => nullableCast + data + "[0]")
                    : null;
            }

            return underlying switch
            {
                "ushort" => new ModbusTypeInfo(typeName, 1, (data, _) => nullableCast + data + "[0]"),
                "short" => new ModbusTypeInfo(typeName, 1, (data, _) => nullableCast + "unchecked((short)" + data + "[0])"),
                "uint" => new ModbusTypeInfo(typeName, 2, (data, swap) => nullableCast + ToUInt32Expression(data, swap)),
                "int" => new ModbusTypeInfo(typeName, 2, (data, swap) => nullableCast + "unchecked((int)" + ToUInt32Expression(data, swap) + ")"),
                "float" => new ModbusTypeInfo(typeName, 2, (data, swap) => nullableCast + "global::ModbusRx.Utility.ModbusUtility.ReadSingle(new global::System.ReadOnlySpan<ushort>(" + data + ", 0, 2), " + ToBoolLiteral(swap) + ")"),
                "double" => new ModbusTypeInfo(typeName, 4, (data, swap) => nullableCast + "global::ModbusRx.Utility.ModbusUtility.ReadDouble(new global::System.ReadOnlySpan<ushort>(" + data + ", 0, 4), " + ToBoolLiteral(swap) + ")"),
                _ => null,
            };
        }

        private static string ToUInt32Expression(string data, bool swapWords)
        {
            var high = swapWords ? data + "[1]" : data + "[0]";
            var low = swapWords ? data + "[0]" : data + "[1]";
            return "(((uint)" + high + " << 16) | " + low + ")";
        }

        private static string ToBoolLiteral(bool value) => value ? "true" : "false";
    }

    private enum ModbusPointKind
    {
        None,
        HoldingRegister,
        InputRegister,
        Coil,
        DiscreteInput,
    }
}

internal static class Nullable
{
    public static string? GetUnderlyingTypeName(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is INamedTypeSymbol named &&
            named.IsGenericType &&
            named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            return named.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        return null;
    }
}
