name: ModbusRx CI-BuildOnly

on:
  push:
    branches-ignore:
      - main

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

    - name: Add MSBuild to PATH
      uses: glennawatson/setup-msbuild@v1.0.3
      with:
        prerelease: true

    - name: NBGV
      id: nbgv
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - run: echo 'SemVer2=${{ steps.nbgv.outputs.SemVer2 }}'

    - name: NuGet Restore
      run: dotnet restore ModbusRx.sln
      working-directory: src

    - name: Build
      run: msbuild /t:build,pack /nowarn:MSB4011 /maxcpucount /p:NoPackageAnalysis=true /verbosity:minimal /p:Configuration=Release ModbusRx.sln
      working-directory: src

    - name: Run Unit Tests and Generate Coverage
      uses: glennawatson/coverlet-msbuild@v1
      with:
        project-files: 'src/**/*Tests*.csproj'
        no-build: true
        include-filter: 'ModbusRx*'
        output-format: cobertura
        configuration: Release

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v3

    - name: Create NuGet Artifacts
      uses: actions/upload-artifact@master
      with:
        name: nuget
        path: '**/*.nupkg'
